global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector-metrics'
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: 'otel-exported-app-metrics'
    static_configs:
      - targets: ['otel-collector:9464']
